### ISSUE TITLE
about routes

### ISSUE THREAD

**Issue by calderaro** [okbel/basicAPI#1]
in my project i have a very similar structure but the routes are slightly different i just want to know what is better.

i have something like this:

``` javascript
router.get('/posts', posts.list);
router.get('/post/:_id', posts.get);
router.post('/post', posts.add);
router.del('/post', posts.del);
router.put('/post', posts.edit);
```

**Comment by okbel** [comment]
It's different because I'm not making a real delete in my del post, so that's why I need two PUT endpoints. I choose to make it that way so I can keep track of what has been hidden. Also, I made the router more descriptive, if I want to add a post I use /post/add routing to give to the API user a more friendly URL API.

**Comment by okbel** [comment]
Next commit will have Ember Routing Convention

**Comment by okbel** [comment]
Ready (: 

Action  HTTP Verb   URL
Find            GET             /posts/123
Find All    GET             /posts
Update  PUT             /posts/123
Create  POST            /posts
Delete  DELETE      /posts/123

Now the routes have been modified, the controller and the model, following Ember Routing Convention.

Thank you!
